# Generated by Django 5.2.5 on 2025-11-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
