# Generated by Django 5.2.5 on 2025-09-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_rating_product_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
