# Generated by Django 5.2.5 on 2025-09-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colors',
        ),
    ]
